### ISSUE TITLE
Allow tickets to be printed at one ticket per page

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-ticketing#4]
See original Codebase ticket for more details https://events.codebasehq.com/projects/event-espresso/tickets/8487

Per @lorenzocaum 

Summary
Could we offer an option to set tickets to be one per page?

Here are some examples of what is happening:

http://cl.ly/image/3M1o0q0F2X2l

http://ee4m.eventespresso.com/?ee=ee-txn-tickets-url&token=1-403e896309f0901d3cafcd99d46a797a

http://cl.ly/153x2C023e3S/All%20tickets%20for%20the%20transaction%3A%20462.pdf

Reported
http://eventespresso.com/topic/single-ticket-per-printer-page/

Per @nerrad 
Looks like this may be something that will work: http://stackoverflow.com/questions/1664049/can-i-force-a-page-jump-in-html-printing

**Comment by lorenzocaum** [comment]
Another member asked about this: https://secure.helpscout.net/conversation/596159382/536821?folderId=284418

**Comment by lorenzocaum** [comment]
This came up on Event Smart again.

**Comment by joshfeck** [comment]
See #6
